version: "3.3"
services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
#      - $PWD/site:/srv

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    hostname: "postgres"
    expose:
      - "5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: 20m

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    environment:
      REACT_APP_SERVER_HOST: ${REACT_APP_SERVER_HOST}
      REACT_APP_SERVER_PORT: ${REACT_APP_SERVER_PORT}
      REACT_APP_SERVER_PROTOCOL: ${REACT_APP_SERVER_PROTOCOL}
      REACT_APP_SERVER_STYLE_FOLDER: ${REACT_APP_SERVER_STYLE_FOLDER}
      REACT_APP_SERVER_REGISTER_FOLDER: ${REACT_APP_SERVER_REGISTER_FOLDER}
      REACT_APP_SERVER_LOGIN_FOLDER: ${REACT_APP_SERVER_LOGIN_FOLDER}
      REACT_APP_SERVER_WEBSOCKET_PROTOCOL: ${REACT_APP_SERVER_WEBSOCKET_PROTOCOL}
      REACT_APP_SERVER_WEBSOCKET_PATH: ${REACT_APP_SERVER_WEBSOCKET_PATH}
      ACC_TOKEN_COOKIE: ${ACC_TOKEN_COOKIE}
      PORT: 3000
    depends_on:
      - "server"
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: 20m

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      MODELS_SYNC_TYPE: ${MODELS_SYNC_TYPE}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      COOKIE_NAME: ${COOKIE_NAME}
      SECURE_COOKIES: ${SECURE_COOKIES}
      ACCESS_TOKEN_EXPIRATION_TIME: ${ACCESS_TOKEN_EXPIRATION_TIME}
      REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}
      CLIENT_HOST: ${CLIENT_HOST}
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_PROTOCOL: ${CLIENT_PROTOCOL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: 20m

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: 'volume'
      o: 'bind'
      device: '${PWD}/volumes/postgres-data/'
